### ISSUE TITLE
"Not enough matic" message showing when I have plenty of Matic

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/uploader-ui-lib#92]
"Not enough matic" message showing when I have plenty of Matic. There is 2.6 Matic in my wallet (which is plently) when this message is shown. 

![image](https://github.com/oceanprotocol/uploader-ui-lib/assets/20739535/ef1e588f-b072-40a5-af1f-1f1b14bf3f90)

**Comment by EnzoVezzaro** [comment]
still investigating 👍🏽 made some tests, but on my end is working correctly.

**Comment by EnzoVezzaro** [comment]
haven't been able to reproduce this. We need to check line 64 on the file src/components/WrapMatic/index.tsx with @jamiehewitt15 's wallet to see what's returning.

**Comment by EnzoVezzaro** [comment]
@jamiehewitt15 are you still experiencing the same issue?

**Comment by jamiehewitt15** [comment]
Yeah, I'm still getting the same issue. I tested with a wallet that has 69 Matic and still seeing that same error message about "Not enough Matic"

**Comment by EnzoVezzaro** [comment]
I'm so confused 😤 I'm not able to replicate this. What do you see in console?
> check line 64 on the file src/components/WrapMatic/index.tsx

On my end: 
https://www.loom.com/share/f30d0ab353504df7ad1bb04b7d247cae?sid=14b85ecc-fbb9-4ee5-823c-ad0813cc41f8

**Comment by EnzoVezzaro** [comment]
@jamiehewitt15 can you please check if in this [PR](https://github.com/oceanprotocol/uploader-ui-lib/pull/95) the issue is solved.

**Comment by jamiehewitt15** [comment]
Still getting the same "Not enough Matic" message on that PR preview link (see the screenshot below, which includes the console logs). 

![image](https://github.com/oceanprotocol/uploader-ui-lib/assets/20739535/8e272af2-104d-4782-873c-a079e1d42ed2)

**Comment by jamiehewitt15** [comment]
It is probably caused by the hook calling useBalance() before the wallet is connected and then it doesn't call it again after the wallet is connected. It only shows up when I first connect the account. If I refresh the page it goes away.

**Comment by jamiehewitt15** [comment]
I added some logs to debug this. Initially, the response is from useBalance undefined which sets the error message and then the logic inside the useEffect has no way to remove the error message once the balance data is received: 

```typescript
  useEffect(() => {
    if (!balanceWallet?.value || balanceWallet.value < props.amount) {
      setError(true)
      setErrorMessage('Not enough matic!')
    } else if (wmaticIsError) {
      setError(true)
      setErrorMessage('Error wMatic. Check logs.')
      console.log(wmaticError)
    }
  }, [balanceWallet, wmaticIsError])
```

![image](https://github.com/oceanprotocol/uploader-ui-lib/assets/20739535/cb39253a-22be-4bc3-8e9c-fd45bbe385d9)


I'll create a PR to fix this

**Comment by EnzoVezzaro** [comment]
> I'll create a PR to fix this

Great. Not sure why this is not happening on my end 🤷🏽‍♂️ I should see the same thing.
